site_name: Rational Functions Documentation
site_url: https://stur86.github.io/rational-functions/
repo_url: https://github.com/stur86/rational-functions
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Numerical accuracy: numerical_accuracy.md
  - API:
    - Polynomial Root: api/polyroot.md
    - Rational Term: api/term.md
    - Rational Function: api/ratfunc.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
  - autorefs
# Math support
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - javascript/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
